### ISSUE TITLE
Add SCIPsetObjsense

### ISSUE THREAD

**Issue by charlene-videoamp** [SCIP-Interfaces/JSCIPOpt#11]
I added two calls: setMaximize and setMinimize which call SCIPsetObjsense and they seem to work. Can I have permission to create a pull request?

**Comment by mattmilten** [comment]
The GitHub way to do this is as follows: You create a fork to have your own JSCIPOpt repo. There you push your new commit to a new branch and then submit a pull request to us for that branch.

Have a look here for further information: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by mueldgog** [comment]
addwed with #12
