### ISSUE TITLE
Installation of JSCIPOpt for Windows and IntelliJ

### ISSUE THREAD

**Issue by hklarner** [SCIP-Interfaces/JSCIPOpt#17]
We have some trouble setting up JSCIPOpt under Windows and IntelliJ. The error message is an unsatisfied link:
```
Main Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Backend\JSCIPOptTest\lib\jscip.dll: Can't find dependent libraries
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at Main.main(Main.java:9)
```
Steps that we have completed successfully:
- we created a new Java project in which we want to use JSCIPOpt
- installation of Visual Studio 2019
- cmake.exe .. -G "Visual Studio 16 2019" -DSCIP_DIR="C:\Program Files\SCIPOptSuite 6.0.2\build"
- we copied `jscip.dll` and `scip.jar` into a folder `"lib"` in our project
- we added the folder `"lib"` to our class path ("project structure"  > "Library" > "+" `"lib"`)

OS:
- Windows 10 64bit
- IDE: IntelliJ Community 2019.1

The message `Can't find dependent libraries` sounds like we are missing additional libraries. What can we try next?

**Comment by mueldgog** [comment]
Did you add `<absolute path to SCIP Optimization Suite>/build/bin/{Release,Debug}` to the PATH variable of Windows?

**Comment by hklarner** [comment]
When installing SCIPOptSuite 6.0.2 in windows we get the error:
```
Warning! PATH too long installer unable to modify PATH!
```
Have you seen this before? What can we do?

**Comment by mueldgog** [comment]
No, I have never seen this before. From [this](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=4775&p=0&start=0&view=), I would guess that it is not related to SCIP.

**Comment by hklarner** [comment]
Right. When installing `SCIPOptSuite-6.0.2-win64-VS15.exe` and _not adding to path_ the installation finishes with a SCIP suite folder that contains three folders:
- bin
- include
- lib
inside `bin` there are four files:
- `scip.dll`
- scip.exe`
- `soplex.exe`
- `zimpl.exe`

Does this look correct to you? It is missing the `/build/bin//Release` part of the path you mentioned above

**Comment by hklarner** [comment]
Ok. We fiddled again with the IntelliJ PATH settings and added the path to the `bin` folder and now it works.

**Comment by mueldgog** [comment]
The structure of the directories looks correct. I just wanted to say that the documentation only mentions the build directory, but sure, you can also install SCIP.

**Comment by mueldgog** [comment]
Very good! I'm not to familiar with Java, but making JSCIPOpt work on Windows seems to be a tough nut.
