### ISSUE TITLE
any method can find the reason why infeasible

### ISSUE THREAD

**Issue by zhengdi1992** [SCIP-Interfaces/JSCIPOpt#20]
an easy case :
if i have put constraint 1    x1 > 4
and also put constraint 2  x1 = 3
then i solve it.. of course infeasible

jscipopt has any method or log info can help us quickly find the reason which confilct by constraint1 and constraint2?
because sometimes, we may not know the silly thing we had done. may be the modeling data was very huge..

any good advice for us to do?  when we find the infeasible result.  thanks a lot.

**Comment by mueldgog** [comment]
Unfortunately, no. There is no API method that you could use for this. Usually, one would try to compute a minimal infeasible constraint set by replacing the objective function by a sum of binary variables that are used to "disable" constraints. For the i-th linear constraint a_i'x <= b_i you would add M * z_i to the right-hand side. z_i is a binary variable and M a constant that is sufficiently large.

For more details, you might want to have a look at https://scip.zib.de/doc-6.0.2/html/MINIISC_MAIN.php and check the corresponding literature that is mentioned.
