### ISSUE TITLE
还需要windows8.1的sdk

### ISSUE THREAD

**Issue by YYMMYB** [SCIP-Interfaces/JSCIPOpt#23]
首先, 我要说明我是新手.

我按照install.md文件中的指导, 在windows10上构建.dll, .jar的时候, 出了错误.
经过搜索后, 我下载并安装windows8.1的sdk后, 再进行构建, 就没有错误了.

所以我觉得可能需要windows8.1的sdk

不够我并不确定我的想法.

Google Translation:

First of all, I want to show that I am a novice.

When I followed the instructions in the install.md file, when building .dll, .jar on windows10, something went wrong.

After searching, I downloaded and installed the windows8.1 SDK, and then built it, and there were no errors.

So I think it may need windows8.1 sdk

Not enough I am not sure what I think.

**Comment by mueldgog** [comment]
Yes, the Visual Studio Windows SDK is required because you need to compile SCIP on your own. I might change the setup such that one can also use our Windows installer.
