### ISSUE TITLE
how to set init solution before solve?

### ISSUE THREAD

**Issue by zhengdi1992** [SCIP-Interfaces/JSCIPOpt#24]
for the title..i want to know how to set one or more solution first before solve?
in the `scipjnijni`, just found `SCIPsetSolVals(long jarg1, long jarg2, int jarg3, long jarg4, long jarg5)` , does it?

but any examples? thanks a lot. :)

**Comment by mueldgog** [comment]
You need to have a look at `JSCIPOpt/java/Scip.java`. There you find some methods to create and add solutions to SCIP. Basically, you need to create a solution via `solution = scip.createSol()`, then set solution values via `scip.setSolVal(...)` or `scip.setSolVals()`, and finally add the solution to SCIP via `scip.addSolFree()`.
