### ISSUE TITLE
how to use FiberSCIP to solve integer programming model from Java?

### ISSUE THREAD

**Issue by usact** [SCIP-Interfaces/JSCIPOpt#26]
Hi, 

I am trying to solve an Integer programming model by running java scip from IntelliJ Idea (community 2019.2) on macbook pro. 

My java is 11. 
My scipoptsuite: 6.0.2.
My jscip cheked out from https://github.com/SCIP-Interfaces/JSCIPOpt

My integer programming model took long time to be solved by SCIP solver. 

Based on this 
https://scip.zib.de/workshop2014/parascip_libraries.pdf

I would like to find how to use FiberSCIP to improve the performance.

Could anyone help me with this or point out some docs that may be helpful?

thanks

David

**Comment by mueldgog** [comment]
This question has been answered on the mailing list.
