### ISSUE TITLE
undefined symbol: gzopen

### ISSUE THREAD

**Issue by ZhiguoLong** [SCIP-Interfaces/JSCIPOpt#5]
When I call `readProb("filename")` to read an `.lp` file, I got this error:
```
java: symbol lookup error: /path/to/JSCIPOpt/lib/../lib/libscipopt.so: undefined symbol: gzopen
```
I have checked reading `.lp` file with SCIT itself and it works well.

Could you please check this?

**Comment by mueldgog** [comment]
Are you sure that your link to the libscipopt.so library is correct? `/path/to/...` looks wrong. Can you try to compile the SCIP Optimization Suite with ZLIB=false?

**Comment by ZhiguoLong** [comment]
Thanks. I compiled with `ZLIB=false` and it works now. I wonder what is the consequence without ZLIB? Will the performance or precision be reduced?

`/path/to...` is actually a symlink to the libscipopt.so library. This symlink is created following the instruction  in [INSTALL.md](https://github.com/SCIP-Interfaces/JSCIPOpt/blob/master/INSTALL.md).

**Comment by mueldgog** [comment]
In Ubuntu you can instlal ZLIB via `sudo apt-get install zlib1g-dev`, then ZLIB=true shouldn't be a problem.
